feat(eternal_history.sh): update and switch from rage (Rust) to age (Go)

diff --git a/run_200.eternal_history.sh.tmpl b/run_200.eternal_history.sh.tmpl
--- a/run_200.eternal_history.sh.tmpl
+++ b/run_200.eternal_history.sh.tmpl
@@ -12,7 +12,7 @@ script_name=$(basename "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}")
 # chezmoi
 if ! command -v chezmoi &> /dev/null; then
   echo >&2 "$script_name: 'chezmoi' is required but it's not installed:
-  https://github.com/twpayne/chezmoi/blob/master/docs/INSTALL.md"
+  https://www.chezmoi.io/install/"
   exit 1
 fi
 
@@ -23,21 +23,25 @@ if ! command -v jq &> /dev/null; then
   exit 1
 fi
 
-# rage
-if ! command -v rage &> /dev/null; then
-  echo >&2 "$script_name: 'rage' is required but it's not installed:
-  https://github.com/str4d/rage#installation"
+# age
+if ! command -v age &> /dev/null; then
+  echo >&2 "$script_name: 'age' is required but it's not installed:
+  https://github.com/FiloSottile/age"
   exit 1
 fi
 
 archive_destination=$(chezmoi data | jq --exit-status --raw-output '.chezmoi.sourceDir')
-rage_recipient='{{ onepasswordRead "op://Personal/bash-eternal - rage-keygen/Public key" "my.1password.com" | trim }}'
+age_recipient='{{ onepasswordRead "op://Personal/bash-eternal - age-keygen/Public key" "my.1password.com" | trim }}'
 
-# Tar, GZip, and encrypt (with (r)age) the eternal history file
+# Tar, GZip, and encrypt (with age) the eternal history file
 tar -cvz --options='compression-level=9' "$HOME/.bash_eternal_history" \
-  | rage --recipient "$rage_recipient" > "$archive_destination/bash_eternal_history.tar.gz.age"
+  | age --recipient "$age_recipient" > "$archive_destination/bash_eternal_history.tar.gz.age"
 
 ### To restore this file:
-# rage --decrypt --identity key.txt --output bash_eternal_history.tar.gz bash_eternal_history.tar.gz.age
-# tar -zxvf bash_eternal_history.tar.gz
+# AGE_KEY=$(gmktemp)
+# op read "op://Private/bash-eternal - rage-keygen/Private key" --account=my.1password.com > "$AGE_KEY"
+# cd "$(chezmoi data | jq --exit-status --raw-output '.chezmoi.sourceDir')"
+# age --decrypt --identity "$AGE_KEY" --output bash_eternal_history.tar.gz bash_eternal_history.tar.gz.age
+# rm --force "$AGE_KEY"
+# tar zxvf bash_eternal_history.tar.gz
 {{- end }}
